-- =============================================================================
-- My City Info — Test Data: Businesses
-- File: database/seed/test/02_test_businesses.sql
--
-- 12 sample business listings across 8 categories:
--   Spark Electricals, CleanNest Home Services, QuickCare Dental Clinic,
--   LifeStep Physiotherapy, Glamour Studio, Urban Spa House,
--   Naveen Famous Veg, Cafe Aroma, Chester Gym & Fitness,
--   Sunrise Hotel Rooms, Property 852, SwiftMove Packers
--
-- DO NOT run on production databases.
--
-- Dependencies (must be seeded first):
--   1. database/seed/master/01_roles_and_system_user.sql
--   2. database/seed_categories.sql
--   3. database/seed_tags.sql
--   4. database/seed/test/01_test_users.sql  (businesses attributed to superadmin UUID)
--
-- Canonical data file: api/v1/migrations/011_seed_businesses.sql
--
-- Command line:
--   mysql -u <user> -p <database> < api/v1/migrations/011_seed_businesses.sql
--
-- MySQL client:
--   SOURCE api/v1/migrations/011_seed_businesses.sql;
-- =============================================================================
