-- =============================================================================
-- Migration 008: Business group and branch schema — My City Info (API v1)
-- Run after: 007_tag_slug.sql
-- Creates 14 new tables for the full business listing data model.
--
-- Primary keys: char(36) UUID v4 — generated by the application (api_uuid_v4()).
-- Exception: join-table FKs pointing to mci_categories and mci_tags keep
-- int unsigned to match those tables' existing INT AUTO_INCREMENT PKs.
--
-- Audit columns on every table:
--   created_at          datetime(6)  — set on INSERT, never changes
--   created_by_user_id  char(36)     — FK → mci_users.id, SET NULL on user delete
--   updated_at          datetime(6)  — auto-updated by MySQL ON UPDATE
--   updated_by_user_id  char(36)     — set by application on every UPDATE, NULL if never updated
--
-- Dependency/creation order:
--   mci_business_groups
--   mci_business_branches
--   mci_business_branch_hours
--   mci_business_subcategories
--   mci_business_tags
--   mci_business_products
--   mci_business_services
--   mci_business_faqs
--   mci_business_images
--   mci_business_social_links
--   mci_business_approvals
--   mci_business_claims
--   mci_business_reviews
--   mci_business_review_replies
-- =============================================================================

SET NAMES utf8mb4;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+00:00';


-- =============================================================================
-- 1) mci_business_groups
--    Shared/inherited data hub for a business entity.
--    All branches reference this record; categories, tags, products, services,
--    FAQs, and images belong here and are inherited by every branch.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_groups` (
  `id`                  char(36)          NOT NULL                             COMMENT 'UUID v4 (primary identifier)',
  `name`                varchar(255)      NOT NULL                             COMMENT 'Business trading name',
  `slug`                varchar(255)      NOT NULL                             COMMENT 'SEO-friendly unique URL segment',
  `tagline`             varchar(255)      DEFAULT NULL                         COMMENT 'Short one-liner / strapline',
  `description`         text              DEFAULT NULL                         COMMENT 'Full about/bio (editorial)',
  `established_year`    year              DEFAULT NULL                         COMMENT 'Year the business was founded',
  `website_url`         varchar(512)      DEFAULT NULL,
  `email`               varchar(255)      DEFAULT NULL                         COMMENT 'General enquiry email',
  -- Images (path + stored pixel dimensions for display/validation reference)
  -- Aspect ratio enforcement is done by the upload handler, not the DB.
  -- Logo      — 1:1  square  — brand mark shown in cards, search results, listing header
  `logo_path`           varchar(512)      DEFAULT NULL                         COMMENT 'Business logo (1:1) — relative file path or CDN URL',
  `logo_width`          smallint unsigned DEFAULT NULL                         COMMENT 'Stored pixel width of uploaded logo',
  `logo_height`         smallint unsigned DEFAULT NULL                         COMMENT 'Stored pixel height of uploaded logo',
  -- Profile   — 1:1  square  — owner / storefront / representative photo
  `profile_path`        varchar(512)      DEFAULT NULL                         COMMENT 'Profile photo (1:1) — relative file path or CDN URL',
  `profile_width`       smallint unsigned DEFAULT NULL                         COMMENT 'Stored pixel width of uploaded profile photo',
  `profile_height`      smallint unsigned DEFAULT NULL                         COMMENT 'Stored pixel height of uploaded profile photo',
  -- Banner    — 16:9 wide    — hero image on business detail page
  `banner_path`         varchar(512)      DEFAULT NULL                         COMMENT 'Banner/hero image (16:9) — relative file path or CDN URL',
  `banner_width`        smallint unsigned DEFAULT NULL                         COMMENT 'Stored pixel width of uploaded banner',
  `banner_height`       smallint unsigned DEFAULT NULL                         COMMENT 'Stored pixel height of uploaded banner',
  `parent_category_id`  int unsigned      NOT NULL                             COMMENT 'FK → mci_categories.id (must be a top-level/root category)',
  `price_range`         enum('free','moderate','pricey','ultra')
                                          DEFAULT NULL,
  `status`              enum('live','draft','suspended','deleted')
                                          NOT NULL DEFAULT 'live'              COMMENT 'cp_admin additions default to live immediately',
  `added_by_role`       enum('cp_admin','subscriber','anonymous')
                                          NOT NULL                             COMMENT 'Business logic: who submitted this listing',
  `added_by_user_id`    char(36)          NOT NULL                             COMMENT 'FK → mci_users.id; use the system anonymous user UUID for anonymous submissions (see migration 009)',
  -- Claim: set when a subscriber successfully claims an anonymous listing
  `claimed_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; subscriber who owns this listing after a successful claim',
  `claimed_at`          datetime(6)       DEFAULT NULL                         COMMENT 'Timestamp when the claim was approved',
  `page_title`          varchar(255)      DEFAULT NULL                         COMMENT 'SEO: HTML <title> override',
  `meta_keywords`       varchar(512)      DEFAULT NULL                         COMMENT 'SEO: meta keywords',
  `meta_description`    varchar(512)      DEFAULT NULL                         COMMENT 'SEO: meta description',
  -- Audit
  `created_at`          datetime(6)       NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)       DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mci_business_groups_slug`             (`slug`),
  KEY        `idx_mci_business_groups_status`            (`status`),
  KEY        `idx_mci_business_groups_parent_category`   (`parent_category_id`),
  KEY        `idx_mci_business_groups_added_by_role`     (`added_by_role`),
  KEY        `idx_mci_business_groups_added_by_user`     (`added_by_user_id`),
  KEY        `idx_mci_business_groups_claimed_by`        (`claimed_by_user_id`),
  KEY        `idx_mci_business_groups_created_by`        (`created_by_user_id`),
  KEY        `idx_mci_business_groups_updated_by`        (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bg_parent_category`
    FOREIGN KEY (`parent_category_id`) REFERENCES `mci_categories` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bg_added_by_user`
    FOREIGN KEY (`added_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bg_claimed_by`
    FOREIGN KEY (`claimed_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bg_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bg_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Shared data hub per business: name, category, SEO, status. All branches inherit from this record. added_by_user_id always references a real mci_users row; use the system anonymous user for anonymous submissions (see migration 009).';


-- =============================================================================
-- 2) mci_business_branches
--    Individual physical locations (all-peer flat model — no primary branch).
--    Each branch has its own listing page (slug), address, and contact details.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_branches` (
  `id`                  char(36)          NOT NULL                             COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)          NOT NULL                             COMMENT 'FK → mci_business_groups.id',
  `branch_label`        varchar(100)      DEFAULT NULL                         COMMENT 'Human label e.g. "Koramangala Branch"; NULL if single location',
  `slug`                varchar(255)      NOT NULL                             COMMENT 'Unique URL segment for this branch listing page',
  `address_line1`       varchar(255)      NOT NULL,
  `address_line2`       varchar(255)      DEFAULT NULL,
  `city`                varchar(100)      NOT NULL,
  `state`               varchar(100)      DEFAULT NULL,
  `country`             varchar(100)      NOT NULL DEFAULT 'India',
  `pincode`             varchar(20)       DEFAULT NULL,
  `latitude`            decimal(10,7)     DEFAULT NULL,
  `longitude`           decimal(10,7)     DEFAULT NULL,
  `phone_primary`       varchar(30)       DEFAULT NULL,
  `phone_secondary`     varchar(30)       DEFAULT NULL,
  `whatsapp_number`     varchar(30)       DEFAULT NULL,
  `is_primary`          tinyint(1)        NOT NULL DEFAULT 0                   COMMENT 'Soft display hint only — not uniquely constrained; flat model has no enforced primary',
  `status`              enum('active','inactive','deleted')
                                          NOT NULL DEFAULT 'active',
  -- Audit
  `created_at`          datetime(6)       NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)       DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mci_business_branches_slug`           (`slug`),
  KEY        `idx_mci_business_branches_group`           (`business_group_id`),
  KEY        `idx_mci_business_branches_status`          (`status`),
  KEY        `idx_mci_business_branches_city`            (`city`),
  KEY        `idx_mci_business_branches_latlong`         (`latitude`, `longitude`),
  KEY        `idx_mci_business_branches_created_by`      (`created_by_user_id`),
  KEY        `idx_mci_business_branches_updated_by`      (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bb_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bb_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bb_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Individual branch/location records. All peers, linked by business_group_id.';


-- =============================================================================
-- 3) mci_business_branch_hours
--    Operating hours per weekday per branch. One row per day (max 7 per branch).
--    NULL opens_at/closes_at when is_closed = 1.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_branch_hours` (
  `id`                  char(36)      NOT NULL                                 COMMENT 'UUID v4 (primary identifier)',
  `branch_id`           char(36)      NOT NULL                                 COMMENT 'FK → mci_business_branches.id',
  `day_of_week`         enum('monday','tuesday','wednesday','thursday','friday','saturday','sunday')
                                      NOT NULL,
  `opens_at`            time          DEFAULT NULL                             COMMENT 'NULL when is_closed = 1',
  `closes_at`           time          DEFAULT NULL                             COMMENT 'NULL when is_closed = 1',
  `is_closed`           tinyint(1)    NOT NULL DEFAULT 0                       COMMENT '1 = branch closed on this day',
  -- Audit
  `created_at`          datetime(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)   DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mci_bbh_branch_day`           (`branch_id`, `day_of_week`),
  KEY        `idx_mci_bbh_branch`                (`branch_id`),
  KEY        `idx_mci_bbh_created_by`            (`created_by_user_id`),
  KEY        `idx_mci_bbh_updated_by`            (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bbh_branch`
    FOREIGN KEY (`branch_id`) REFERENCES `mci_business_branches` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bbh_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bbh_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Operating hours per weekday per branch (up to 7 rows per branch).';


-- =============================================================================
-- 4) mci_business_subcategories
--    Links a business group to one or more child (sub-)categories within its
--    single parent category.
--
--    Note on FK types:
--      business_group_id → char(36)  (UUID, matches mci_business_groups.id)
--      category_id       → int unsigned (matches mci_categories.id which is INT AUTO_INCREMENT)
--
--    APP-LEVEL ENFORCEMENT:
--    category_id MUST reference a row in mci_categories where parent_id IS NOT NULL
--    (i.e. a subcategory, not a root category). The FK alone cannot enforce this.
--    API must verify: SELECT id FROM mci_categories WHERE id = ? AND parent_id IS NOT NULL
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_subcategories` (
  `id`                  char(36)      NOT NULL                                 COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)      NOT NULL                                 COMMENT 'FK → mci_business_groups.id',
  `category_id`         int unsigned  NOT NULL                                 COMMENT 'FK → mci_categories.id (MUST have parent_id IS NOT NULL — enforced at app level)',
  `sort_order`          int           NOT NULL DEFAULT 0,
  -- Audit
  `created_at`          datetime(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)   DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mci_bsc_group_category`       (`business_group_id`, `category_id`),
  KEY        `idx_mci_bsc_group`                 (`business_group_id`),
  KEY        `idx_mci_bsc_category`              (`category_id`),
  KEY        `idx_mci_bsc_created_by`            (`created_by_user_id`),
  KEY        `idx_mci_bsc_updated_by`            (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bsc_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bsc_category`
    FOREIGN KEY (`category_id`) REFERENCES `mci_categories` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bsc_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bsc_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Sub-categories assigned to a business group. App must verify category_id has parent_id IS NOT NULL.';


-- =============================================================================
-- 5) mci_business_tags
--    Many-to-many join: business group ↔ mci_tags.
--
--    Note on FK types:
--      business_group_id → char(36)  (UUID, matches mci_business_groups.id)
--      tag_id            → int unsigned (matches mci_tags.id which is INT AUTO_INCREMENT)
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_tags` (
  `id`                  char(36)      NOT NULL                                 COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)      NOT NULL                                 COMMENT 'FK → mci_business_groups.id',
  `tag_id`              int unsigned  NOT NULL                                 COMMENT 'FK → mci_tags.id',
  -- Audit
  `created_at`          datetime(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)   DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_mci_bt_group_tag`             (`business_group_id`, `tag_id`),
  KEY        `idx_mci_bt_group`                  (`business_group_id`),
  KEY        `idx_mci_bt_tag`                    (`tag_id`),
  KEY        `idx_mci_bt_created_by`             (`created_by_user_id`),
  KEY        `idx_mci_bt_updated_by`             (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bt_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bt_tag`
    FOREIGN KEY (`tag_id`) REFERENCES `mci_tags` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bt_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bt_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Many-to-many: business groups ↔ tags.';


-- =============================================================================
-- 6) mci_business_products
--    Products offered by a business group (inherited by all branches).
--    Supports price range (min/max) and an optional unit label.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_products` (
  `id`                  char(36)          NOT NULL                             COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)          NOT NULL                             COMMENT 'FK → mci_business_groups.id',
  `name`                varchar(255)      NOT NULL,
  `description`         text              DEFAULT NULL,
  `price_min`           decimal(10,2)     DEFAULT NULL,
  `price_max`           decimal(10,2)     DEFAULT NULL,
  `price_unit`          varchar(50)       DEFAULT NULL                         COMMENT 'e.g. "per kg", "per piece"',
  `image_path`          varchar(512)      DEFAULT NULL                         COMMENT 'Relative file path or CDN URL',
  `sort_order`          int               NOT NULL DEFAULT 0,
  `is_active`           tinyint(1)        NOT NULL DEFAULT 1,
  -- Audit
  `created_at`          datetime(6)       NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)       DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  KEY `idx_mci_bp_group`       (`business_group_id`),
  KEY `idx_mci_bp_is_active`   (`is_active`),
  KEY `idx_mci_bp_created_by`  (`created_by_user_id`),
  KEY `idx_mci_bp_updated_by`  (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bp_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bp_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bp_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Products offered by a business group (inherited by all branches).';


-- =============================================================================
-- 7) mci_business_services
--    Services offered by a business group — identical shape to products,
--    kept as a separate table for semantic clarity and independent ordering.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_services` (
  `id`                  char(36)          NOT NULL                             COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)          NOT NULL                             COMMENT 'FK → mci_business_groups.id',
  `name`                varchar(255)      NOT NULL,
  `description`         text              DEFAULT NULL,
  `price_min`           decimal(10,2)     DEFAULT NULL,
  `price_max`           decimal(10,2)     DEFAULT NULL,
  `price_unit`          varchar(50)       DEFAULT NULL                         COMMENT 'e.g. "per hour", "per session"',
  `image_path`          varchar(512)      DEFAULT NULL                         COMMENT 'Relative file path or CDN URL',
  `sort_order`          int               NOT NULL DEFAULT 0,
  `is_active`           tinyint(1)        NOT NULL DEFAULT 1,
  -- Audit
  `created_at`          datetime(6)       NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)       DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)          DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  KEY `idx_mci_bs_group`       (`business_group_id`),
  KEY `idx_mci_bs_is_active`   (`is_active`),
  KEY `idx_mci_bs_created_by`  (`created_by_user_id`),
  KEY `idx_mci_bs_updated_by`  (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bs_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bs_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bs_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Services offered by a business group (inherited by all branches).';


-- =============================================================================
-- 8) mci_business_faqs
--    Frequently asked questions for a business group, ordered by sort_order.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_faqs` (
  `id`                  char(36)      NOT NULL                                 COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)      NOT NULL                                 COMMENT 'FK → mci_business_groups.id',
  `question`            varchar(512)  NOT NULL,
  `answer`              text          NOT NULL,
  `sort_order`          int           NOT NULL DEFAULT 0,
  -- Audit
  `created_at`          datetime(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)   DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)      DEFAULT NULL                             COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  KEY `idx_mci_bfaq_group`       (`business_group_id`),
  KEY `idx_mci_bfaq_created_by`  (`created_by_user_id`),
  KEY `idx_mci_bfaq_updated_by`  (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bfaq_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bfaq_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bfaq_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='FAQs for a business group, ordered by sort_order.';


-- =============================================================================
-- 9) mci_business_images
--    Image gallery attached to a business group (not per-branch).
--
--    LIMITS (enforced at application level — cannot be done via DB CHECK alone):
--      • Max 20 images per business_group_id:
--          API must run SELECT COUNT(*) WHERE business_group_id = ? before INSERT
--          and reject with HTTP 422 if count >= 20.
--      • Max 2 MB per file:
--          Upload handler must validate file size before writing to disk/storage.
--          file_size_bytes is stored here for reference/audit only.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_images` (
  `id`                    char(36)        NOT NULL                             COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`     char(36)        NOT NULL                             COMMENT 'FK → mci_business_groups.id',
  `file_path`             varchar(512)    NOT NULL                             COMMENT 'Relative file path or CDN URL',
  `caption`               varchar(255)    DEFAULT NULL,
  `alt_text`              varchar(255)    DEFAULT NULL                         COMMENT 'Accessibility alt text',
  `is_cover`              tinyint(1)      NOT NULL DEFAULT 0                   COMMENT '1 = primary/cover image for the group',
  `file_size_bytes`       int unsigned    DEFAULT NULL                         COMMENT 'Stored for audit; 2 MB max enforced at app level',
  `sort_order`            int             NOT NULL DEFAULT 0,
  `uploaded_by_user_id`   char(36)        DEFAULT NULL                         COMMENT 'FK → mci_users.id; NULL if uploaded without account context',
  -- Audit
  `created_at`            datetime(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`    char(36)        DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`            datetime(6)     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`    char(36)        DEFAULT NULL                         COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  KEY `idx_mci_bimg_group`        (`business_group_id`),
  KEY `idx_mci_bimg_is_cover`     (`is_cover`),
  KEY `idx_mci_bimg_uploaded_by`  (`uploaded_by_user_id`),
  KEY `idx_mci_bimg_created_by`   (`created_by_user_id`),
  KEY `idx_mci_bimg_updated_by`   (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bimg_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bimg_uploader`
    FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bimg_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bimg_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Image gallery per business group. Max 20 images and max 2 MB per file enforced at application level.';


-- =============================================================================
-- 10) mci_business_social_links
--     Social media profile URLs for a business group (one row per platform).
--     Using a join table rather than columns on mci_business_groups means new
--     platforms can be added by extending the ENUM without an ALTER TABLE on
--     the main groups table.
--
--     Supported platforms: facebook, instagram, twitter, youtube, linkedin,
--     tiktok, pinterest, threads, snapchat, whatsapp_channel, telegram, other.
--     For platform = 'other', use the `label` field to describe the platform.
--
--     UNIQUE (business_group_id, platform) — one URL per platform per business.
--     Exception: 'other' may have multiple rows (UNIQUE not enforced for other).
--     App must enforce the other-platform uniqueness by label if desired.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_social_links` (
  `id`                  char(36)        NOT NULL                               COMMENT 'UUID v4 (primary identifier)',
  `business_group_id`   char(36)        NOT NULL                               COMMENT 'FK → mci_business_groups.id',
  `platform`            enum(
                          'facebook',
                          'instagram',
                          'twitter',
                          'youtube',
                          'linkedin',
                          'tiktok',
                          'pinterest',
                          'threads',
                          'snapchat',
                          'whatsapp_channel',
                          'telegram',
                          'other'
                        )               NOT NULL                               COMMENT 'Social media platform identifier',
  `url`                 varchar(512)    NOT NULL                               COMMENT 'Full URL to the business profile/page/channel',
  `label`               varchar(100)    DEFAULT NULL                           COMMENT 'Human-readable label; required when platform = ''other'' (e.g. "Koo", "ShareChat")',
  `sort_order`          int             NOT NULL DEFAULT 0                     COMMENT 'Display order in UI',
  -- Audit
  `created_at`          datetime(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; user who created this record',
  `updated_at`          datetime(6)     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  -- One URL per named platform per business (other is exempt — handled at app level)
  UNIQUE KEY `uniq_mci_bsl_group_platform`     (`business_group_id`, `platform`),
  KEY        `idx_mci_bsl_group`               (`business_group_id`),
  KEY        `idx_mci_bsl_platform`            (`platform`),
  KEY        `idx_mci_bsl_created_by`          (`created_by_user_id`),
  KEY        `idx_mci_bsl_updated_by`          (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bsl_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bsl_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bsl_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Social media profile links per business group. One row per platform; platform=other allows custom label for unlisted platforms.';


-- =============================================================================
-- 11) mci_business_approvals
--     Immutable audit log of every status transition on a business group.
--     One row is inserted each time a CP admin reviews a listing — whether
--     approving, rejecting, suspending, or reinstating it.
--     The current status always lives on mci_business_groups.status; this
--     table provides the full traceable history with a stable approval_id
--     for future reference (e.g. support tickets, compliance queries).
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_approvals` (
  `id`                  char(36)        NOT NULL                               COMMENT 'UUID v4 — stable approval reference ID',
  `business_group_id`   char(36)        NOT NULL                               COMMENT 'FK → mci_business_groups.id',
  `reviewed_by_user_id` char(36)        NOT NULL                               COMMENT 'FK → mci_users.id; CP admin who performed this action',
  `action`              enum(
                          'approved',
                          'rejected',
                          'suspended',
                          'reinstated',
                          'draft'
                        )               NOT NULL                               COMMENT 'Action taken during this review',
  `previous_status`     enum('live','draft','suspended','deleted')
                                        DEFAULT NULL                           COMMENT 'Status of the listing before this action',
  `new_status`          enum('live','draft','suspended','deleted')
                                        NOT NULL                               COMMENT 'Status after this action',
  `notes`               text            DEFAULT NULL                           COMMENT 'Internal reviewer notes / rejection reason',
  `reviewed_at`         datetime(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6)  COMMENT 'When this review action was taken',

  PRIMARY KEY (`id`),
  KEY `idx_mci_bapprv_group`       (`business_group_id`),
  KEY `idx_mci_bapprv_reviewed_by` (`reviewed_by_user_id`),
  KEY `idx_mci_bapprv_action`      (`action`),
  KEY `idx_mci_bapprv_reviewed_at` (`reviewed_at`),

  CONSTRAINT `fk_mci_bapprv_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bapprv_reviewed_by`
    FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Immutable audit log of every CP review action on a business group. Each row is a stable approval record with a unique ID.';


-- =============================================================================
-- 12) mci_business_claims
--     Workflow table for subscribers claiming ownership of a business listing.
--     A claim is raised against a business group (typically one added anonymously
--     or by a CP admin). CP admin reviews the claim and approves or rejects it.
--     On approval: mci_business_groups.claimed_by_user_id + claimed_at are set,
--     and the claimant gains subscriber-level management access to the listing.
--     Original added_by_user_id is never overwritten (audit preserved).
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_claims` (
  `id`                  char(36)        NOT NULL                               COMMENT 'UUID v4 — stable claim reference ID',
  `business_group_id`   char(36)        NOT NULL                               COMMENT 'FK → mci_business_groups.id',
  `claimant_user_id`    char(36)        NOT NULL                               COMMENT 'FK → mci_users.id; subscriber raising the claim',
  `status`              enum(
                          'pending',
                          'under_review',
                          'approved',
                          'rejected',
                          'withdrawn'
                        )               NOT NULL DEFAULT 'pending',
  `claim_message`       text            DEFAULT NULL                           COMMENT 'Claimant''s explanation / proof of ownership',
  `supporting_doc_path` varchar(512)    DEFAULT NULL                           COMMENT 'Optional uploaded proof document (file path or CDN URL)',
  -- Resolution
  `reviewed_by_user_id` char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; CP admin who resolved this claim',
  `reviewed_at`         datetime(6)     DEFAULT NULL                           COMMENT 'When the claim was approved or rejected',
  `reviewer_notes`      text            DEFAULT NULL                           COMMENT 'Internal CP admin notes on the claim decision',
  -- Audit
  `created_at`          datetime(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by_user_id`  char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; same as claimant_user_id in practice',
  `updated_at`          datetime(6)     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  KEY `idx_mci_bclaim_group`       (`business_group_id`),
  KEY `idx_mci_bclaim_claimant`    (`claimant_user_id`),
  KEY `idx_mci_bclaim_status`      (`status`),
  KEY `idx_mci_bclaim_reviewed_by` (`reviewed_by_user_id`),
  KEY `idx_mci_bclaim_created_by`  (`created_by_user_id`),
  KEY `idx_mci_bclaim_updated_by`  (`updated_by_user_id`),

  CONSTRAINT `fk_mci_bclaim_group`
    FOREIGN KEY (`business_group_id`) REFERENCES `mci_business_groups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bclaim_claimant`
    FOREIGN KEY (`claimant_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bclaim_reviewed_by`
    FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bclaim_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_bclaim_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Claim workflow: subscriber requests ownership of a listing. CP admin approves/rejects. On approval, mci_business_groups.claimed_by_user_id is set.';


-- =============================================================================
-- 13) mci_business_reviews
--     Ratings and reviews per branch (each location rated independently).
--     Only logged-in subscribers can submit reviews (reviewer_user_id NOT NULL).
--     One review per subscriber per branch enforced via UNIQUE constraint.
--     Rating: 1–5 stars (enforced by CHECK constraint, MySQL 8.0.16+).
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_reviews` (
  `id`                  char(36)        NOT NULL                               COMMENT 'UUID v4 (primary identifier)',
  `branch_id`           char(36)        NOT NULL                               COMMENT 'FK → mci_business_branches.id; reviews are per branch location',
  `reviewer_user_id`    char(36)        NOT NULL                               COMMENT 'FK → mci_users.id; subscriber who wrote this review',
  `rating`              tinyint unsigned NOT NULL                              COMMENT '1–5 star rating (CHECK constraint enforced)',
  `title`               varchar(255)    DEFAULT NULL                           COMMENT 'Optional short headline for the review',
  `body`                text            DEFAULT NULL                           COMMENT 'Full review text',
  `is_verified_visit`   tinyint(1)      NOT NULL DEFAULT 0                     COMMENT '1 = reviewer has been verified as a real customer (future use)',
  `status`              enum('published','hidden','flagged')
                                        NOT NULL DEFAULT 'published',
  -- Moderation
  `moderated_by_user_id` char(36)       DEFAULT NULL                           COMMENT 'FK → mci_users.id; CP admin who moderated this review',
  `moderated_at`        datetime(6)     DEFAULT NULL,
  `moderation_notes`    text            DEFAULT NULL                           COMMENT 'Internal notes if hidden or flagged',
  -- Audit
  `created_at`          datetime(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at`          datetime(6)     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; user who last modified this record',

  PRIMARY KEY (`id`),
  -- One review per subscriber per branch
  UNIQUE KEY `uniq_mci_brev_branch_user`     (`branch_id`, `reviewer_user_id`),
  KEY        `idx_mci_brev_branch`           (`branch_id`),
  KEY        `idx_mci_brev_reviewer`         (`reviewer_user_id`),
  KEY        `idx_mci_brev_status`           (`status`),
  KEY        `idx_mci_brev_rating`           (`rating`),
  KEY        `idx_mci_brev_moderated_by`     (`moderated_by_user_id`),
  KEY        `idx_mci_brev_updated_by`       (`updated_by_user_id`),

  -- Rating must be 1–5 (MySQL 8.0.16+ CHECK constraint)
  CONSTRAINT `chk_mci_brev_rating` CHECK (`rating` BETWEEN 1 AND 5),

  CONSTRAINT `fk_mci_brev_branch`
    FOREIGN KEY (`branch_id`) REFERENCES `mci_business_branches` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_brev_reviewer`
    FOREIGN KEY (`reviewer_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_brev_moderated_by`
    FOREIGN KEY (`moderated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_brev_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Ratings and reviews per branch location. One review per subscriber per branch. Rating 1–5 enforced by CHECK constraint.';


-- =============================================================================
-- 14) mci_business_review_replies
--     Business owner replies to reviews.
--     Only the claimed owner (mci_business_groups.claimed_by_user_id) or a
--     CP admin may post a reply. One reply per review (UNIQUE on review_id).
--     The app must enforce ownership before allowing a reply INSERT.
-- =============================================================================
CREATE TABLE IF NOT EXISTS `mci_business_review_replies` (
  `id`                  char(36)        NOT NULL                               COMMENT 'UUID v4 (primary identifier)',
  `review_id`           char(36)        NOT NULL                               COMMENT 'FK → mci_business_reviews.id',
  `replied_by_user_id`  char(36)        NOT NULL                               COMMENT 'FK → mci_users.id; claimed owner or CP admin who replied',
  `replied_by_role`     enum('owner','cp_admin')
                                        NOT NULL                               COMMENT 'Role context of the replier at time of reply',
  `body`                text            NOT NULL                               COMMENT 'Reply text',
  `status`              enum('published','hidden')
                                        NOT NULL DEFAULT 'published',
  -- Audit
  `created_at`          datetime(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at`          datetime(6)     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by_user_id`  char(36)        DEFAULT NULL                           COMMENT 'FK → mci_users.id; user who last edited this reply',

  PRIMARY KEY (`id`),
  -- One reply per review
  UNIQUE KEY `uniq_mci_brev_reply_review`    (`review_id`),
  KEY        `idx_mci_brevreply_replied_by`  (`replied_by_user_id`),
  KEY        `idx_mci_brevreply_status`      (`status`),
  KEY        `idx_mci_brevreply_updated_by`  (`updated_by_user_id`),

  CONSTRAINT `fk_mci_brevreply_review`
    FOREIGN KEY (`review_id`) REFERENCES `mci_business_reviews` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_brevreply_replied_by`
    FOREIGN KEY (`replied_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT `fk_mci_brevreply_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `mci_users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Business owner or CP admin reply to a review. One reply per review enforced by UNIQUE constraint. App must verify replier is the claimed owner or a CP admin.';
