CREATE TABLE IF NOT EXISTS mci_business_flags (
  id                  char(36) NOT NULL,
  business_group_id   char(36) NOT NULL,
  reporter_user_id    char(36) DEFAULT NULL,
  reporter_type       enum('logged_in','guest','anonymous') NOT NULL DEFAULT 'anonymous',
  reporter_name       varchar(160) DEFAULT NULL,
  reporter_email      varchar(254) DEFAULT NULL,
  reason              text NOT NULL,
  status              enum('open','resolved','dismissed') NOT NULL DEFAULT 'open',
  admin_note          text DEFAULT NULL,
  resolved_by_user_id char(36) DEFAULT NULL,
  resolved_at         datetime(6) DEFAULT NULL,
  created_at          datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_user_id  char(36) DEFAULT NULL,
  updated_at          datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by_user_id  char(36) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_mci_bflag_group (business_group_id),
  KEY idx_mci_bflag_reporter (reporter_user_id),
  KEY idx_mci_bflag_status (status),
  KEY idx_mci_bflag_resolved_by (resolved_by_user_id),
  KEY idx_mci_bflag_created_by (created_by_user_id),
  KEY idx_mci_bflag_updated_by (updated_by_user_id),
  CONSTRAINT fk_mci_bflag_group FOREIGN KEY (business_group_id) REFERENCES mci_business_groups (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_mci_bflag_reporter FOREIGN KEY (reporter_user_id) REFERENCES mci_users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_mci_bflag_resolved_by FOREIGN KEY (resolved_by_user_id) REFERENCES mci_users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_mci_bflag_created_by FOREIGN KEY (created_by_user_id) REFERENCES mci_users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_mci_bflag_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES mci_users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

